# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MargheritaApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MargheritaApp

end

target 'MargheritaApp WatchKit App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MargheritaApp WatchKit App

end

target 'MargheritaApp WatchKit Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MargheritaApp WatchKit Extension

pod 'Alamofire'

end
